export enum FeaturesRoutingEnum {
  Contact = 'contact',
  Dashboard = 'dashboard',
  EmailSent = 'email-sent',
  ExpiredPassword = 'expired-password',
  FAQ = 'faq',
  Guardian = 'responsable-legal',
  LegalPages = 'legals',
  LostPassword = 'lost-password',
  MailList = 'mail-list',
  NotAuthorized = '401',
  NotFound = '404',
  Onboarding = 'onboarding',
  Profile = 'profile',
  ReactivateAccount = 'reactivate-account',
  Redirect = 'redirect',
  ResetPassword = 'reset-password',
  Services = 'services',
  Sign = 'sign',
  SignUp = 'sign-up',
  TechnicalError = '500',
  Sso = 'sso',
}
